### ISSUE TITLE
No packages under catkinws/src

### ISSUE THREAD

**Issue by bwehbe** [Daaboulex/RIS-Lab-1-uuv_simulator#1]
there is no code committed under the source directory with the answers of tasks 2 and 3. Please add the code you described in the report for proper evaluation of your assignment

**Comment by Daaboulex** [comment]
Appologies for this issue. For some reason, GitHub did not let us push this file last time. I will reupload the files in a moment.

**Comment by Daaboulex** [comment]
> there is no code committed under the source directory with the answers of tasks 2 and 3. Please add the code you described in the report for proper evaluation of your assignment

Apologies for this issue. For some reason, GitHub did not let us push this file last time. I will reupload the files in a moment.
